version: "3"
services:
  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=NO
      - GRANT_SUDO=yes
    volumes:
      - ../:/home/jovyan/work
