[package]
name = "rust_playground"
version = "0.1.0"
authors = ["leriou <yange1876@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
redis = "0.16.0"
elasticsearch = "7.8.0-alpha.1"
serde = "~1"
serde_json = "~1"
tokio = { version = "0.2", features = ["full"] }
